name: 2025-mdibl-fair
channels:
  - conda-forge
  - bioconda
platforms:
  - linux-64
  - osx-64
dependencies:
  - python=3.11
  - conda-lock=2.5
  - multiqc=1.29
  - snakemake=9.5.1
  - fastp=0.26.0
  - fastqc=0.12.1
  - salmon=1.10.3
