name: Build Docker on PR and Push to GitHub Container Registry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Only build if the workflow, Dockerfile, renv.lock, or requirements.txt is modified
on:
  push:
    branches:
      - main
    paths:
        - Dockerfile
        - renv.lock
        - requirements.txt
        - .github/workflows/build-*.yaml
  pull_request:
    branches:
      - main
    paths:
        - Dockerfile
        - renv.lock
        - requirements.txt
        - .github/workflows/build-*.yaml
  workflow_dispatch:

jobs:
  build-docker-images:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-push-docker.yml
    with:
      push-ghcr: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
